# Generated by Django 3.1.4 on 2020-12-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_complaint_favouritevoting_votefact_votefactvariant_votevariant_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
