# Generated by Django 3.1.4 on 2021-01-11 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_voting_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='finished',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='voting',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
