# Generated by Django 3.1.5 on 2021-01-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_auto_20210111_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='type',
            field=models.IntegerField(default=2),
        ),
    ]
