# Generated by Django 3.1.5 on 2021-01-29 13:51

import django.db.models.deletion
from django.db import migrations, models

import main.models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_auto_20210128_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=main.models.image_directory_path),
        ),
    ]
