# Generated by Django 3.1.5 on 2021-01-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0009_folovers'),
    ]

    operations = [
        migrations.AddField(
            model_name='folovers',
            name='to_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='folovers',
            name='folover',
            field=models.IntegerField(default=0),
        ),
    ]
